### ISSUE TITLE
Broken link for theia api plugins 

### ISSUE THREAD

**Issue by kittaakos** [eclipse-theia/theia-website#129]
Originally reported by @irohitb [here](https://github.com/eclipse-theia/theia/issues/8859#issue-765972044):

> ### Bug Description:
> Api of the plugins report 404 page not found when navigating from Authoring plugin
> 
> ### Steps to Reproduce:
> 1. Visit [this link](https://theia-ide.org/docs/authoring_plugins)
> 2. Browse to API of plug-ins Section
> 3. Click on Browse typedoc of plug-ins link
> 
> <img alt="Screenshot 2020-12-14 at 11 52 22 AM" width="1440" src="https://user-images.githubusercontent.com/32276134/102047186-d63b4f80-3e02-11eb-897b-59aa1155e214.png">

**Comment by irohitb** [comment]
Another link which is broken: https://theia-ide.org/docs/Services_and_Contributions.md#dependency-injection-di

Found here: https://theia-ide.org/docs/authoring_extensions

Following line: 
>In Theia, everything is wired up via [dependency injection](https://theia-ide.org/docs/Services_and_Contributions.md#dependency-injection-di
).

**Comment by JonasHelming** [comment]
> Another link which is broken: https://theia-ide.org/docs/Services_and_Contributions.md#dependency-injection-di
> 
> Found here: https://theia-ide.org/docs/authoring_extensions
> 
> Following line:
> 
> > In Theia, everything is wired up via [dependency injection](https://theia-ide.org/docs/Services_and_Contributions.md#dependency-injection-di).
> 
> This (dependency injection link) should be fixed #130 pull request

This one is fixed via https://github.com/eclipse-theia/theia-website/issues/144

**Comment by ucg8j** [comment]
👋 I'm still getting a 404 for this one
<img width="1076" alt="image" src="https://user-images.githubusercontent.com/6220504/155891148-eab7466d-b910-4fc3-8998-114081c8f3bc.png">
